chore: add github action summary

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,8 +14,10 @@ jobs:
   check-release:
     runs-on: ubuntu-latest
     outputs:
-      tag: ${{ steps.release.outputs.tag }}
+      tag: ${{ steps.github-release.outputs.tag }}
+      release_url: ${{ steps.github-releases.outputs.url }}
       new: ${{ steps.verify.outputs.new }}
+      dockerhub_available: ${{ steps.docker-verify.outputs.found }}
 
     steps:
       - name: Validate SemVer Tag
@@ -28,29 +30,53 @@ jobs:
             exit 1
           fi
 
-      - name: Nextcloud Docker release
-        id: release
+      - name: GitHub Nextcloud Docker release
+        id: github-release
         run: |
           if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
             API_URL="https://api.github.com/repos/nextcloud/server/releases/tags/v${{ github.event.inputs.tag }}"
           else
             API_URL="https://api.github.com/repos/nextcloud/server/releases/latest"
           fi
+          echo
 
-          TAG=$(curl -s --fail "$API_URL" | jq -r .tag_name || echo "unknown")
+          rsp=$(curl -fs "$API_URL" || echo "unknown")
+          if [[ "$TAG" == "unknown" ]]; then
+            echo "Failed to fetch release from \"$API_URL\""
+          fi
 
-          if [[ "$TAG" == "null" || -z "$TAG" || "$TAG" == "unknown" ]]; then
-            echo "Failed to fetch release from \"$API_URL\". Exiting..."
+          TAG=$(echo "$rsp" | jq -r ".tag_name")
+          if [[ "$TAG" == "null" || -z "$TAG" ]]; then
+            echo "Tag name not found in release response"
             exit 1
           fi
 
-          echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
+          RELEASE_URL=$(echo "$rsp" | jq -r ".html_url")
+          if [[ "$RELEASE_URL" == "null" || -z "$RELEASE_URL" ]]; then
+            echo "Release URL not found in release response"
+            exit 1
+          fi
 
-      - name: Check if tag exists
+          echo "tag=${TAG:1}" >> $GITHUB_OUTPUT
+          echo "url=$RELEASE_URL" >> $GITHUB_OUTPUT
+
+      # Docker release might take a while to be released
+      - name: Check if Docker Nextcloud tag exists
+        id: docker-verify
+        run: |
+          rsp=$(curl -sI -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/namespaces/library/repositories/nextcloud/tags/${{ steps.github-release.outputs.tag }}")
+          if [ "$rsp" -eq 200 ]; then
+            echo "found=true" >> $GITHUB_OUTPUT
+          else
+            echo "found=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Check if tag already published
+        if: ${{ steps.docker-verify.outputs.found == 'true' }}
         id: verify
         run: |
-          RESPONSE=$(curl -s -o /dev/null -I -w "%{http_code}" "https://hub.docker.com/v2/namespaces/library/repositories/nextcloud/tags/$LATEST_RELEASE")
-          if [ "$RESPONSE" -eq 200 ]; then
+          rsp=$(curl -sI -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/namespaces/datahearth/repositories/nextcloud-docker/tags/${{ steps.github-release.outputs.tag }}")
+          if [ "$rsp" -eq 200 ]; then
             echo "new=false" >> $GITHUB_OUTPUT
           else
             echo "new=true" >> $GITHUB_OUTPUT
@@ -60,6 +86,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: check-release
     if: ${{ needs.check-release.outputs.new == 'true' }}
+    outputs:
+      tags: ${{ steps.meta.outputs.tags }}
+      labels: ${{ steps.meta.outputs.labels }}
 
     steps:
       - name: Checkout
@@ -91,9 +120,54 @@ jobs:
 
       - name: Build and push
         uses: docker/build-push-action@v6
+        env:
+          DOCKER_BUILD_SUMMARY: false
         with:
           build-args: |
             NEXTCLOUD_VERSION=${{ needs.check-release.outputs.tag }}
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+  summary:
+    runs-on: ubuntu-latest
+    needs: [check-release, publish-release]
+    if: always()
+
+    steps:
+      - name: Summary
+        run: |
+          echo "# 🚀 Summary" >> $GITHUB_STEP_SUMMARY
+
+          echo "## 🔍 Checking Job" >> $GITHUB_STEP_SUMMARY
+          if [[ "${{ needs.check-release.result }}" == "success" ]]; then
+            echo "Status: ✅ Success" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Status: ❌ Failed" >> $GITHUB_STEP_SUMMARY
+          fi
+
+          echo "Github release: ${{ needs.check-release.outputs.release_url }}\n" >> $GITHUB_STEP_SUMMARY
+
+          if [[ "${{ github.event }}" == "workflow_dispatch" ]]; then
+            echo "- Tag validation: ✅" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "${{ needs.check-release.outputs.dockerhub_available }}" == "true" ]]; then
+            echo "- Docker Hub release: ✅" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "- Docker Hub release: ❌" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "${{ needs.check-release.outputs.new }}" == "true" ]]; then
+            echo "- Already published: ✅" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "- Already published: ❌" >> $GITHUB_STEP_SUMMARY
+          fi
+
+
+          echo "## 🐳 Docker Image Publishing" >> $GITHUB_STEP_SUMMARY
+          if [[ "${{ needs.publish.result }}" == "success" ]]; then
+            echo "Status: ✅ Successfully Published\n" >> $GITHUB_STEP_SUMMARY
+            echo "- Tags ${{ needs.publish-release.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
+            echo "- Labels: ${{ needs.publish-release.outputs.labels }}" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Status: ❌ Failed to Publish" >> $GITHUB_STEP_SUMMARY
+          fi
