fix: summary

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,26 +11,29 @@ on:
         description: Nextcloud SemVer tag to build and publish (MAJOR.MINOR.PATCH)
 
 jobs:
+  validate-tag:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'workflow_dispatch'
+
+    steps:
+      - name: Validate SemVer Tag
+        run: |
+          if [[ ! "${{ github.event.inputs.tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            exit 1
+          fi
+
   check-release:
     runs-on: ubuntu-latest
+    needs: validate-tag
+    if: needs.validate-tag.result == 'skipped' || needs.validate-tag.result == 'success'
     outputs:
       tag: ${{ steps.github-release.outputs.tag }}
-      release_url: ${{ steps.github-releases.outputs.url }}
+      release_url: ${{ steps.github-release.outputs.url }}
       new: ${{ steps.verify.outputs.new }}
       dockerhub_available: ${{ steps.docker-verify.outputs.found }}
 
     steps:
-      - name: Validate SemVer Tag
-        if: ${{ github.event_name == 'workflow_dispatch' }}
-        id: validate_version
-        run: |
-          TAG="${{ github.event.inputs.tag }}"
-          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid tag format: $TAG"
-            exit 1
-          fi
-
-      - name: GitHub Nextcloud Docker release
+      - name: GitHub release
         id: github-release
         run: |
           if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
@@ -38,11 +41,11 @@ jobs:
           else
             API_URL="https://api.github.com/repos/nextcloud/server/releases/latest"
           fi
-          echo
 
           rsp=$(curl -fs "$API_URL" || echo "unknown")
-          if [[ "$TAG" == "unknown" ]]; then
+          if [[ "$rsp" == "unknown" ]]; then
             echo "Failed to fetch release from \"$API_URL\""
+            exit 1
           fi
 
           TAG=$(echo "$rsp" | jq -r ".tag_name")
@@ -60,8 +63,7 @@ jobs:
           echo "tag=${TAG:1}" >> $GITHUB_OUTPUT
           echo "url=$RELEASE_URL" >> $GITHUB_OUTPUT
 
-      # Docker release might take a while to be released
-      - name: Check if Docker Nextcloud tag exists
+      - name: Docker release
         id: docker-verify
         run: |
           rsp=$(curl -sI -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/namespaces/library/repositories/nextcloud/tags/${{ steps.github-release.outputs.tag }}")
@@ -71,8 +73,8 @@ jobs:
             echo "found=false" >> $GITHUB_OUTPUT
           fi
 
-      - name: Check if tag already published
-        if: ${{ steps.docker-verify.outputs.found == 'true' }}
+      - name: Check tag already published
+        if: steps.docker-verify.outputs.found == 'true'
         id: verify
         run: |
           rsp=$(curl -sI -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/namespaces/datahearth/repositories/nextcloud-docker/tags/${{ steps.github-release.outputs.tag }}")
@@ -85,7 +87,7 @@ jobs:
   publish-release:
     runs-on: ubuntu-latest
     needs: check-release
-    if: ${{ needs.check-release.outputs.new == 'true' }}
+    if: needs.check-release.outputs.new == 'true'
     outputs:
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
@@ -131,7 +133,7 @@ jobs:
 
   summary:
     runs-on: ubuntu-latest
-    needs: [check-release, publish-release]
+    needs: [validate-tag, check-release, publish-release]
     if: always()
 
     steps:
@@ -139,35 +141,46 @@ jobs:
         run: |
           echo "# 🚀 Summary" >> $GITHUB_STEP_SUMMARY
 
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            if [[ "${{ needs.validate-tag.result }}" == "success" ]]; then
+              echo "Tag validation: ✅" >> $GITHUB_STEP_SUMMARY
+            elif [[ "${{ needs.validate-tag.result }}" == "skipped" ]]; then
+              echo "Status: ⭕ Skipped" >> $GITHUB_STEP_SUMMARY
+            else
+              echo "Status: ❌ Failed" >> $GITHUB_STEP_SUMMARY
+            fi
+          fi
+
           echo "## 🔍 Checking Job" >> $GITHUB_STEP_SUMMARY
-          if [[ "${{ needs.check-release.result }}" == "success" ]]; then
-            echo "Status: ✅ Success" >> $GITHUB_STEP_SUMMARY
+          if [[ "${{ needs.validate-tag.result }}" == "failure" ]]; then
+            echo "Status: ⭕ Skipped" >> $GITHUB_STEP_SUMMARY
           else
-            echo "Status: ❌ Failed" >> $GITHUB_STEP_SUMMARY
-          fi
+            if [[ "${{ needs.check-release.result }}" == "success" ]]; then
+              echo "Status: ✅ Success" >> $GITHUB_STEP_SUMMARY
+              echo "Github release: [${{ needs.check-release.outputs.tag }}](${{ needs.check-release.outputs.release_url }})" >> $GITHUB_STEP_SUMMARY
 
-          echo "Github release: ${{ needs.check-release.outputs.release_url }}\n" >> $GITHUB_STEP_SUMMARY
-
-          if [[ "${{ github.event }}" == "workflow_dispatch" ]]; then
-            echo "- Tag validation: ✅" >> $GITHUB_STEP_SUMMARY
+              if [[ "${{ needs.check-release.outputs.dockerhub_available }}" == "true" ]]; then
+                echo "- Docker Hub release: ✅" >> $GITHUB_STEP_SUMMARY
+              else
+                echo "- Docker Hub release: ❌" >> $GITHUB_STEP_SUMMARY
+              fi
+              if [[ "${{ needs.check-release.outputs.new }}" == "true" ]]; then
+                echo "- Already published: ❌" >> $GITHUB_STEP_SUMMARY
+              else
+                echo "- Already published: ✅" >> $GITHUB_STEP_SUMMARY
+              fi
+            else
+              echo "Status: ❌ Failed" >> $GITHUB_STEP_SUMMARY
+            fi
           fi
-          if [[ "${{ needs.check-release.outputs.dockerhub_available }}" == "true" ]]; then
-            echo "- Docker Hub release: ✅" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "- Docker Hub release: ❌" >> $GITHUB_STEP_SUMMARY
-          fi
-          if [[ "${{ needs.check-release.outputs.new }}" == "true" ]]; then
-            echo "- Already published: ✅" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "- Already published: ❌" >> $GITHUB_STEP_SUMMARY
-          fi
-
 
           echo "## 🐳 Docker Image Publishing" >> $GITHUB_STEP_SUMMARY
-          if [[ "${{ needs.publish.result }}" == "success" ]]; then
+          if [[ "${{ needs.publish-release.result }}" == "success" ]]; then
             echo "Status: ✅ Successfully Published\n" >> $GITHUB_STEP_SUMMARY
             echo "- Tags ${{ needs.publish-release.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
             echo "- Labels: ${{ needs.publish-release.outputs.labels }}" >> $GITHUB_STEP_SUMMARY
+          elif [[ "${{ needs.publish-release.result }}" == "skipped" ]]; then
+            echo "Status: ⭕ Skipped" >> $GITHUB_STEP_SUMMARY
           else
             echo "Status: ❌ Failed to Publish" >> $GITHUB_STEP_SUMMARY
           fi
